version: '3.8'

services:
  php-api:
    build: ./php-api
    ports:
      - "9090:80"
    volumes:
      - ./php-api:/var/www/html

  node-socket:
    build: ./node-socket
    ports:
      - "4000:3000"
    volumes:
      - ./node-socket:/app
      - /app/node_modules

  frontend:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - php-api
      - node-socket
